<!DOCTYPE html>
<html>
<head>
<title>Student Information</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<h2>Student Input Form </h2>
<form action="DisplayDetails_2.jsp">
<table>
<tr>
<td>Student ID :</td>
<td><input type="text" name="studentid" required/><br/></td>
</tr>
<tr>
<td>Student Name :</td>
<td><input type="text" name="studentname" required/><br/></td>
</tr>
<tr>
<td>Student Enrolled Programm :</td>
<td><input type="text" name="studentprogram" required/><br/></td>
</tr>
<tr>
<td>Student Semester :</td>
<td><input type="text" name="studentsemester" required/><br/></td>
</tr>
<tr>
<td> Java Marks out of 100 :</td>
<td><input type="text" name="marks1" required/><br/></td>
</tr>
<tr>
<td>PHP Marks  out of 100: </td>
<td><input type="text" name="marks2" required/><br/></td>
</tr>
<tr>
<td>.Net Marks  out of 100:</td>
<td><input type="text" name="marks3" required/><br/></td>
</tr>
<tr>
<td><input type="submit" value="Calculate Grade"/></td>
</tr>
</table>
</form>
</body>
</html>
