<html>
<head>
<title>TODO supply a title</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<h2>
            Page Scope sharing <br/></h2>
<form action="pagescopesharing.jsp">
                Music Genere <input type="text" name="musicgenre"/><br/>
                Artist Name <input type="text" name="artistname"/><br/>
<input type="submit" value="Submit"/><br/>
</form>

</body>
</html>
