package src;
public class MusicBean 
{
    private String musicgenre="Pop Music";
    private String artistname="Michael Jackson";

    public String getMusicgenre() {
        return musicgenre;
    }

    public void setMusicgenre(String musicgenre) {
this.musicgenre = musicgenre;
    }

    public String getArtistname() {
        return artistname;
    }

    public void setArtistname(String artistname) {
this.artistname = artistname;
    }

}
