<!DOCTYPE html>
<html>
<head>
<title>Sharing Bean</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<h2>
            Request Scope sharing <br/></h2>
<form action="requestscopesharing.jsp">
                Music Genre <input type="text" name="musicgenre"/><br/>
                Artist Name <input type="text" name="artistname"/><br/>
<input type="submit" value="Submit"/><br/>
</form>

</body>
</html>
