public class CourseDetails 
{
    String programName,semesterNumber,courseId,courseName;

    public String getProgramName() {
        return programName;
    }

    public void setProgramName(String programName) {
this.programName = programName;
    }

    public String getSemesterNumber() {
        return semesterNumber;
    }

    public void setSemesterNumber(String semesterNumber) {
this.semesterNumber = semesterNumber;
    }

    public String getCourseId() {
        return courseId;
    }

    public void setCourseId(String courseId) {
this.courseId = courseId;
    }

    public String getCourseName() {
        return courseName;
    }

    public void setCourseName(String courseName) {
this.courseName = courseName;
    }

}
