<!DOCTYPE html>
<html>
<head>
<title>Ternary Operator usage</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<h1>Student Marks Entry form</h1>
<form action="StudentMarks" method="post" >
<table>
<tr>
<td>Student ID :</td>
<td><input type="text" name="txtid"/></td>
</tr>
<tr>
<td>Student Name :</td>
<td><input type="text" name="txtname"/></td>
</tr>
<tr>
<td>Java :</td>
<td><input type="text" name="txtmarks1"/></td>
</tr>
<tr>
<td>Php :</td>
<td><input type="text" name="txtmarks2"/></td>
</tr>
<tr>
<td>.Net :</td>
<td><input type="text" name="txtmarks3"/></td>
</tr>
<tr>
<td colspan="2" align="center"><input type="submit" value="Calulate 
Grade"/></td>
</tr>
</table>
</form>
</body>
</html>
