package src;
public class Student {
    String studentid,studentname;
    double marks1,marks2,marks3;
    String grade;

    public String getStudentid() {
        return studentid;
    }

    public void setStudentid(String studentid) {
this.studentid = studentid;
    }

    public String getStudentname() {
        return studentname;
    }

    public void setStudentname(String studentname) {
this.studentname = studentname;
    }

    public double getMarks1() {
        return marks1;
    }

    public void setMarks1(double marks1) {
this.marks1 = marks1;
    }

    public double getMarks2() {
        return marks2;
    }

    public void setMarks2(double marks2) {
this.marks2 = marks2;
    }

    public double getMarks3() {
        return marks3;
    }

    public void setMarks3(double marks3) {
this.marks3 = marks3;
    }

    public String getGrade() {
        return grade;
    }

    public void setGrade(String grade) {
this.grade = grade;
    }
    }
