<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <h2>Login</h2>
        <form action="Login.jsp" method="post">
          Username :  <input type="text" name="uname"/><br/>
          Password :  <input type="password" name="pwd"/><br/>
          <input type="submit" value="Login"/>    
        </form>
    </body>
</html>

